### ISSUE TITLE
Create Composer tutorial

### ISSUE THREAD

**Issue by crispinread** [wdanuk/curriculum#32]

**Comment by danharper83** [comment]
Can do tutorial, but then walk through that as part of the lesson?

**Comment by crispinread** [comment]
yeah that sounds good - we need to be getting more resources like this for people that miss lessons eh

**Comment by danharper83** [comment]
Created a code example for this, complete and incomplete where do you think the best place to put it is?

**Comment by crispinread** [comment]
hmmm yeh maybe we need a separate private repo for trainer materials? I'll create one for now and we can have a think about how best to do this long-term

**Comment by danharper83** [comment]
In an effort to keep the issue list tidy can we close this as v1 complete?

**Comment by crispinread** [comment]
yes absolute
